<?php
// +----------------------------------------------------------------------
// | 海豚PHP框架 [ DolphinPHP ]
// +----------------------------------------------------------------------
// | 版权所有 2016~2019 广东卓锐软件有限公司 [ http://www.zrthink.com ]
// +----------------------------------------------------------------------
// | 官方网站: http://dolphinphp.com
// +----------------------------------------------------------------------

/**
 * 菜单信息
 */
return [
	[
		'title' => '音乐',
		'icon' => '',
		'url_type' => 'module_admin',
		'url_value' => 'music/index/index',
		'url_target' => '_self',
		'online_hide' => '0',
		'sort' => '100',
		'status' => '1',
		'child' => [
			[
				'title' => '歌单列表',
				'icon' => '',
				'url_type' => 'module_admin',
				'url_value' => 'music/index/index',
				'url_target' => '_self',
				'online_hide' => '0',
				'sort' => '100',
				'status' => '1',
				'child' => [
					[
						'title' => '新增',
						'icon' => '',
						'url_type' => 'module_admin',
						'url_value' => 'music/index/add',
						'url_target' => '_self',
						'online_hide' => '0',
						'sort' => '100',
						'status' => '1',
					],
					[
						'title' => '编辑',
						'icon' => '',
						'url_type' => 'module_admin',
						'url_value' => 'music/index/edit',
						'url_target' => '_self',
						'online_hide' => '0',
						'sort' => '100',
						'status' => '1',
					],
					[
						'title' => '删除',
						'icon' => '',
						'url_type' => 'module_admin',
						'url_value' => 'music/index/delete',
						'url_target' => '_self',
						'online_hide' => '0',
						'sort' => '100',
						'status' => '1',
					],
					[
						'title' => '生成mv',
						'icon' => '',
						'url_type' => 'module_admin',
						'url_value' => 'music/index/mv',
						'url_target' => '_self',
						'online_hide' => '0',
						'sort' => '100',
						'status' => '1',
					],
					[
						'title' => '下载最新歌曲',
						'icon' => '',
						'url_type' => 'module_admin',
						'url_value' => 'music/index/download',
						'url_target' => '_self',
						'online_hide' => '0',
						'sort' => '100',
						'status' => '1',
					],
					[
						'title' => '快速编辑',
						'icon' => '',
						'url_type' => 'module_admin',
						'url_value' => 'queue/index/quickedit',
						'url_target' => '_self',
						'online_hide' => '0',
						'sort' => '100',
						'status' => '1',
					],
				],
			],
			[
				'title' => '歌曲列表',
				'icon' => '',
				'url_type' => 'module_admin',
				'url_value' => 'music/music/index',
				'url_target' => '_self',
				'online_hide' => '0',
				'sort' => '100',
				'status' => '1',
				'child' => [
					[
						'title' => '新增',
						'icon' => '',
						'url_type' => 'module_admin',
						'url_value' => 'music/music/add',
						'url_target' => '_self',
						'online_hide' => '0',
						'sort' => '100',
						'status' => '1',
					],
					[
						'title' => '编辑',
						'icon' => '',
						'url_type' => 'module_admin',
						'url_value' => 'music/music/edit',
						'url_target' => '_self',
						'online_hide' => '0',
						'sort' => '100',
						'status' => '1',
					],
					[
						'title' => '删除',
						'icon' => '',
						'url_type' => 'module_admin',
						'url_value' => 'music/music/delete',
						'url_target' => '_self',
						'online_hide' => '0',
						'sort' => '100',
						'status' => '1',
					],
//					[
//						'title' => '生成mv',
//						'icon' => '',
//						'url_type' => 'module_admin',
//						'url_value' => 'music/index/mv',
//						'url_target' => '_self',
//						'online_hide' => '0',
//						'sort' => '100',
//						'status' => '1',
//					],
//					[
//						'title' => '下载最新歌曲',
//						'icon' => '',
//						'url_type' => 'module_admin',
//						'url_value' => 'music/index/download',
//						'url_target' => '_self',
//						'online_hide' => '0',
//						'sort' => '100',
//						'status' => '1',
//					],
					[
						'title' => '快速编辑',
						'icon' => '',
						'url_type' => 'module_admin',
						'url_value' => 'queue/index/quickedit',
						'url_target' => '_self',
						'online_hide' => '0',
						'sort' => '100',
						'status' => '1',
					],
				],
			],
		],
	],
];
